export type CardType =
    | "artifact"
    | "battle"
    | "conspiracy"
    | "creature"
    | "dungeon"
    | "enchantment"
    | "instant"
    | "kindred"
    | "land"
    | "phenomenon"
    | "plane"
    | "planeswalker"
    | "scheme"
    | "sorcery"
    | "vanguard";
