export type Subtype =
    | ArtifactType
    | EnchantmentType
    | LandType
    | PlaneswalkerType
    | SpellType
    | CreatureType
    | PlanarType
    | DungeonType
    | BattleType;

/** アーティファクト・タイプ */
export type ArtifactType = (typeof artifact_types)[number];
const artifact_types = [
    "Attraction",
    "Blood",
    "Bobblehead",
    "Clue",
    "Contraption",
    "Equipment",
    "Food",
    "Fortification",
    "Gold",
    "Incubator",
    "Infinity",
    "Junk",
    "Lander",
    "Map",
    "Powerstone",
    "Spacecraft",
    "Stone",
    "Treasure",
    "Vehicle",
] as const;

/** エンチャント・タイプ */
export type EnchantmentType = (typeof enchantment_types)[number];
const enchantment_types = [
    "Aura",
    "Background",
    "Cartouche",
    "Case",
    "Class",
    "Curse",
    "Role",
    "Room",
    "Rune",
    "Saga",
    "Shard",
    "Shrine",
] as const;

/** 土地タイプ */
export type LandType = (typeof land_types)[number];
const land_types = [
    "Cave",
    "Desert",
    "Forest",
    "Gate",
    "Island",
    "Lair",
    "Locus",
    "Mine",
    "Mountain",
    "Plains",
    "Planet",
    "Power-Plant",
    "Sphere",
    "Swamp",
    "Tower",
    "Town",
    "Urza’s",
] as const;

/** プレインズウォーカー・タイプ */
export type PlaneswalkerType = (typeof planeswalker_types)[number];
const planeswalker_types = [
    "Ajani",
    "Aminatou",
    "Angrath",
    "Arlinn",
    "Ashiok",
    "Bahamut",
    "Basri",
    "Bolas",
    "Calix",
    "Chandra",
    "Comet",
    "Dack",
    "Dakkon",
    "Daretti",
    "Davriel",
    "Dihada",
    "Domri",
    "Dovin",
    "Ellywick",
    "Elminster",
    "Elspeth",
    "Estrid",
    "Freyalise",
    "Garruk",
    "Gideon",
    "Grist",
    "Guff",
    "Huatli",
    "Jace",
    "Jared",
    "Jaya",
    "Jeska",
    "Kaito",
    "Karn",
    "Kasmina",
    "Kaya",
    "Kiora",
    "Koth",
    "Liliana",
    "Lolth",
    "Lukka",
    "Minsc",
    "Mordenkainen",
    "Nahiri",
    "Narset",
    "Niko",
    "Nissa",
    "Nixilis",
    "Oko",
    "Quintorius",
    "Ral",
    "Rowan",
    "Saheeli",
    "Samut",
    "Sarkhan",
    "Serra",
    "Sivitri",
    "Sorin",
    "Szat",
    "Tamiyo",
    "Tasha",
    "Teferi",
    "Teyo",
    "Tezzeret",
    "Tibalt",
    "Tyvar",
    "Ugin",
    "Urza",
    "Venser",
    "Vivien",
    "Vraska",
    "Vronos",
    "Will",
    "Windgrace",
    "Wrenn",
    "Xenagos",
    "Yanggu",
    "Yanling",
    "Zariel",
] as const;

/** 呪文タイプ */
export type SpellType = (typeof spell_types)[number];
const spell_types = ["Adventure", "Arcane", "Lesson", "Omen", "Trap"] as const;

/** クリーチャー・タイプ */
export type CreatureType = (typeof creature_types)[number];
const creature_types = [
    "Time Lord",
    "Advisor",
    "Aetherborn",
    "Alien",
    "Ally",
    "Angel",
    "Antelope",
    "Ape",
    "Archer",
    "Archon",
    "Armadillo",
    "Army",
    "Artificer",
    "Assassin",
    "Assembly-Worker",
    "Astartes",
    "Atog",
    "Aurochs",
    "Avatar",
    "Azra",
    "Badger",
    "Balloon",
    "Barbarian",
    "Bard",
    "Basilisk",
    "Bat",
    "Bear",
    "Beast",
    "Beaver",
    "Beeble",
    "Beholder",
    "Berserker",
    "Bird",
    "Blinkmoth",
    "Boar",
    "Bringer",
    "Brushwagg",
    "Camarid",
    "Camel",
    "Capybara",
    "Caribou",
    "Carrier",
    "Cat",
    "Centaur",
    "Child",
    "Chimera",
    "Citizen",
    "Cleric",
    "Clown",
    "Cockatrice",
    "Construct",
    "Coward",
    "Coyote",
    "Crab",
    "Crocodile",
    "C’tan",
    "Custodes",
    "Cyberman",
    "Cyclops",
    "Dalek",
    "Dauthi",
    "Demigod",
    "Demon",
    "Deserter",
    "Detective",
    "Devil",
    "Dinosaur",
    "Djinn",
    "Doctor",
    "Dog",
    "Dragon",
    "Drake",
    "Dreadnought",
    "Drix",
    "Drone",
    "Druid",
    "Dryad",
    "Dwarf",
    "Echidna",
    "Efreet",
    "Egg",
    "Elder",
    "Eldrazi",
    "Elemental",
    "Elephant",
    "Elf",
    "Elk",
    "Employee",
    "Eye",
    "Faerie",
    "Ferret",
    "Fish",
    "Flagbearer",
    "Fox",
    "Fractal",
    "Frog",
    "Fungus",
    "Gamer",
    "Gargoyle",
    "Germ",
    "Giant",
    "Gith",
    "Glimmer",
    "Gnoll",
    "Gnome",
    "Goat",
    "Goblin",
    "God",
    "Golem",
    "Gorgon",
    "Graveborn",
    "Gremlin",
    "Griffin",
    "Guest",
    "Hag",
    "Halfling",
    "Hamster",
    "Harpy",
    "Hedgehog",
    "Hellion",
    "Hero",
    "Hippo",
    "Hippogriff",
    "Homarid",
    "Homunculus",
    "Horror",
    "Horse",
    "Human",
    "Hydra",
    "Hyena",
    "Illusion",
    "Imp",
    "Incarnation",
    "Inkling",
    "Inquisitor",
    "Insect",
    "Jackal",
    "Jellyfish",
    "Juggernaut",
    "Kavu",
    "Kirin",
    "Kithkin",
    "Knight",
    "Kobold",
    "Kor",
    "Kraken",
    "Llama",
    "Lamia",
    "Lammasu",
    "Leech",
    "Leviathan",
    "Lhurgoyf",
    "Licid",
    "Lizard",
    "Lobster",
    "Manticore",
    "Masticore",
    "Mercenary",
    "Merfolk",
    "Metathran",
    "Minion",
    "Minotaur",
    "Mite",
    "Mole",
    "Monger",
    "Mongoose",
    "Monk",
    "Monkey",
    "Moogle",
    "Moonfolk",
    "Mount",
    "Mouse",
    "Mutant",
    "Myr",
    "Mystic",
    "Nautilus",
    "Necron",
    "Nephilim",
    "Nightmare",
    "Nightstalker",
    "Ninja",
    "Noble",
    "Noggle",
    "Nomad",
    "Nymph",
    "Octopus",
    "Ogre",
    "Ooze",
    "Orb",
    "Orc",
    "Orgg",
    "Otter",
    "Ouphe",
    "Ox",
    "Oyster",
    "Pangolin",
    "Peasant",
    "Pegasus",
    "Pentavite",
    "Performer",
    "Pest",
    "Phelddagrif",
    "Phoenix",
    "Phyrexian",
    "Pilot",
    "Pincher",
    "Pirate",
    "Plant",
    "Porcupine",
    "Possum",
    "Praetor",
    "Primarch",
    "Prism",
    "Processor",
    "Qu",
    "Rabbit",
    "Raccoon",
    "Ranger",
    "Rat",
    "Rebel",
    "Reflection",
    "Rhino",
    "Rigger",
    "Robot",
    "Rogue",
    "Sable",
    "Salamander",
    "Samurai",
    "Sand",
    "Saproling",
    "Satyr",
    "Scarecrow",
    "Scientist",
    "Scion",
    "Scorpion",
    "Scout",
    "Sculpture",
    "Seal",
    "Serf",
    "Serpent",
    "Servo",
    "Shade",
    "Shaman",
    "Shapeshifter",
    "Shark",
    "Sheep",
    "Siren",
    "Skeleton",
    "Skunk",
    "Slith",
    "Sliver",
    "Sloth",
    "Slug",
    "Snail",
    "Snake",
    "Soldier",
    "Soltari",
    "Spawn",
    "Specter",
    "Spellshaper",
    "Sphinx",
    "Spider",
    "Spike",
    "Spirit",
    "Splinter",
    "Sponge",
    "Squid",
    "Squirrel",
    "Starfish",
    "Surrakar",
    "Survivor",
    "Symbiote",
    "Synth",
    "Tentacle",
    "Tetravite",
    "Thalakos",
    "Thopter",
    "Thrull",
    "Tiefling",
    "Toy",
    "Treefolk",
    "Trilobite",
    "Triskelavite",
    "Troll",
    "Turtle",
    "Tyranid",
    "Unicorn",
    "Vampire",
    "Varmint",
    "Vedalken",
    "Villain",
    "Volver",
    "Wall",
    "Walrus",
    "Warlock",
    "Warrior",
    "Weasel",
    "Weird",
    "Werewolf",
    "Whale",
    "Wizard",
    "Wolf",
    "Wolverine",
    "Wombat,",
    "Worm,",
    "Wraith,",
    "Wurm,",
    "Yeti,",
    "Zombie,",
    "Zubera",
] as const;

/** 次元タイプ */
export type PlanarType = (typeof planar_types)[number];
const planar_types = [
    "The Abyss",
    "Alara",
    "Alfava Metraxis",
    "Amonkhet",
    "Androzani Minor",
    "Antausia",
    "Apalapucia",
    "Arcavios",
    "Arkhos",
    "Avishkar",
    "Azgol",
    "Belenon",
    "Bolas’s Meditation Realm",
    "Capenna",
    "Cridhe",
    "The Dalek Asylum",
    "Darillium",
    "Dominaria",
    "Earth",
    "Echoir",
    "Eldraine",
    "Equilor",
    "Ergamon",
    "Fabacin",
    "Fiora",
    "Gallifrey",
    "Gargantikar",
    "Gobakhan",
    "Horsehead Nebula",
    "Ikoria",
    "Innistrad",
    "Iquatana",
    "Ir",
    "Ixalan",
    "Kaldheim",
    "Kamigawa",
    "Kandoka",
    "Karsus",
    "Kephalai",
    "Kinshala",
    "Kolbahan",
    "Kylem",
    "Kyneth",
    "The Library",
    "Lorwyn",
    "Luvion",
    "Mars",
    "Mercadia",
    "Mirrodin",
    "Moag",
    "Mongseng",
    "Moon",
    "Muraganda",
    "Necros",
    "New Earth",
    "New Phyrexia",
    "Outside Mutter’s Spiral",
    "Phyrexia",
    "Pyrulea",
    "Rabiah",
    "Rath",
    "Ravnica",
    "Regatha",
    "Segovia",
    "Serra’s Realm",
    "Shadowmoor",
    "Shandalar",
    "Shenmeng",
    "Skaro",
    "Spacecraft",
    "Tarkir",
    "Theros",
    "Time",
    "Trenzalore",
    "Ulgrotha",
    "Unknown Planet",
    "Valla",
    "Vryn",
    "Wildfire",
    "Xerex",
    "Zendikar",
    "Zhalfir",
] as const;

/** ダンジョン・タイプ */
export type DungeonType = (typeof dungeon_types)[number];
const dungeon_types = ["Undercity"];

/** バトル・タイプ */
export type BattleType = (typeof battle_types)[number];
const battle_types = ["Siege"] as const;
